=head1 NAME

Portable BBS

=head2 DESCRIPTION

C<Portable BBS> is very portable web application example.
You can learn how to create portable web application in C<Perl>.

This application have the following features.

=over 2

=item *

Embedded preforking web Server, you can start web application in a minute.

=item * 

Version controll system by L<Test::ModuleVersion>.
you can use whole C<CPAN> module.

Module setup is very easy.
This application use L<DBIx::Custom>, L<Validator::Custom>,
L<DBI>, and L<DBD::SQLite>.

=item *

Windows support. you can run this application on windows, not only linux/unix.

=back

=head1 Setup

Install some moudles.

  perl cpanm -l extlib Module::CoreList
  perl -Iextlib/lib/perl5 t/module.t list --fail | perl cpanm -L extlib

If you don't install all module try force install.

  perl -Iextlib/lib/perl5 t/module.t list --fail | perl cpanm -n -L extlib

=head1 Test

Run test to check setup is ok.

  prove t

If all test is passed, setup is ok.

=head1 Application management

=head2 Start

  ./hypnotoad

Application start in backend. Port number is C<10000> by default.
See L<Mojolicious> hypnotoad command about options.

You can also restart application by same command.

=head2 Stop

  ./hypnotoad --stop

You can stop application by C<--stop> option.

=head2 Start in development

  ./morbo

Application is started in C<development> mode. port is C<3000> by default.

=head1 Windows support

=head2 Start

  set MOJO_MODE=production
  perl script/portablebbs daemon --listen=http://*:10000

If you want to run background,
you can register this application as windows service.

=cut
