=head1 NAME

Portable BBS

=head2 DESCRIPTION

C<Portable BBS> is simple web application example which have following features.

=over 2

=item * Web framework is Mojolicious

=item * Database is SQLite

=item * O/R mapper is DBIx::Custom

=item * Easy setup system by Test::ModuleVersion

=back

=head1 What you can learn from this application?

=over 2

=item * C<Mojolicious> web frame work. routing, template, and controller

=item * Database access using C<SQLite> and C<DBIx::Custom>

=item * Form data validation using C<Validator::Custom>

=item * How to use C<Test::ModuleVersion> to create portable web application

=back

=head1 Setup

Install some moudles.

  $ perl t/module.t list_fail | perl cpanm -L extlib

Check all module is installed.

  $ perl t/module.t

If all test is passed, setup is ok.

=head1 Application start and stop

=head2 C<Start>

  $ perl -Iextlib/lib/perl5 extlib/bin/hypnotoad script/portablebbs

Application start in backend. Port number is C<8080> by default.

=head2 C<Restart>

Restart is same command as start command

  $ perl -Iextlib/lib/perl5 extlib/bin/hypnotoad script/portablebbs

=head2 C<Stop>

You can stop application by C<--stop> option.

  $ perl -Iextlib/lib/perl5 extlib/bin/hypnotoad script/portablebbs --stop

=cut
